-- ============================================================
--  Тест для телесного терапевта — база анкет клиентов
--  Куда вставлять: Supabase → SQL Editor → New query → вставить
--  весь файл целиком → Run. Выполняется один раз.
-- ============================================================

-- Таблица анкет. name/phone вынесены отдельными колонками, чтобы
-- их было видно в Table Editor без разворачивания JSON; вся анкета
-- целиком (со всеми ответами, цепочкой, текстом разбора и т.д.)
-- лежит в data — ровно то же, что видно в админке на сайте.
create table if not exists public.body_test_results (
  id bigint generated by default as identity primary key,
  client_id text not null unique,
  name text not null default '',
  phone text not null default '',
  created_at timestamptz not null default now(),
  data jsonb not null
);

-- Доступ к таблице закрыт полностью — ни читать, ни писать напрямую
-- нельзя (даже с публичным ключом сайта). Работа идёт только через
-- две функции ниже, у каждой свои права.
alter table public.body_test_results enable row level security;
revoke all on public.body_test_results from anon, authenticated;

-- Запись анкеты — вызывается с сайта каждый раз, когда клиент проходит
-- тест или нажимает кнопку («Записаться», «3 урока» и т.д. — сайт
-- дозаписывает, какие кнопки нажали). ON CONFLICT обновляет ту же
-- строку по client_id, а не создаёт новую копию анкеты.
create or replace function public.save_body_result(payload jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.body_test_results (client_id, name, phone, data)
  values (
    payload->>'client_id',
    coalesce(payload->>'name', ''),
    coalesce(payload->>'phone', ''),
    payload
  )
  on conflict (client_id) do update
    set name = excluded.name,
        phone = excluded.phone,
        data = excluded.data;
end;
$$;

-- Чтение всей базы для админки — отдаёт анкеты, только если admin_key
-- совпадает с паролем. ВАЖНО: строка 'telo2026' ниже должна совпадать
-- с ADMIN_PASSWORD в src/config.js — если поменяете пароль в одном
-- месте, поменяйте и здесь, иначе админка перестанет подгружать базу.
create or replace function public.get_body_results(admin_key text)
returns setof public.body_test_results
language plpgsql
security definer
set search_path = public
as $$
begin
  if admin_key is distinct from 'telo2026' then
    raise exception 'forbidden';
  end if;
  return query select * from public.body_test_results order by created_at desc;
end;
$$;

-- Публичный ключ сайта (anon) может только вызывать эти две функции —
-- саму таблицу напрямую (SELECT/INSERT/UPDATE/DELETE) он не видит.
grant execute on function public.save_body_result(jsonb) to anon;
grant execute on function public.get_body_results(text) to anon;
